"""create_tables

Revision ID: 3478b48f6dc3
Revises: 374c08d1ef2d
Create Date: 2026-05-26 23:03:11.323144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = '3478b48f6dc3'
down_revision: Union[str, Sequence[str], None] = '374c08d1ef2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue_events',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.CHAR(length=255), nullable=True),
    sa.Column('attachment_id', sa.String(length=255), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('time_posted', sa.DateTime(), nullable=True),
    sa.Column('parent_event_id', sa.Uuid(), nullable=True),
    sa.Column('time_updated', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['parent_event_id'], ['issue_events.event_id'], name='issue_events_parent_event_id_fkey'),
    sa.PrimaryKeyConstraint('event_id', name='issue_events_pkey')
    )
    op.create_table('issues',
    sa.Column('issue_id', sa.Uuid(), nullable=False),
    sa.Column('issue_title', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=10), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('visibility', sa.Enum('private', 'public', name='issue_visibility'), nullable=True),
    sa.Column('status', sa.Enum('pending', 'resolved', name='issue_status'), nullable=True),
    sa.Column('issue_eta', sa.DateTime(), nullable=True),
    sa.Column('department', sa.Enum('horticulture', 'engineering unit', name='department_enum'), nullable=True),
    sa.Column('embeddings', pgvector.sqlalchemy.vector.VECTOR(dim=50), nullable=True),
    sa.Column('priority_score_base', sa.Integer(), nullable=True),
    sa.Column('priority_score', sa.Integer(), nullable=True),
    sa.Column('escalations', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.PrimaryKeyConstraint('issue_id', name='issues_pkey')
    )
    op.create_table('users',
    sa.Column('user_id', sa.CHAR(length=255), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('role', sa.Enum('student', 'faculty', 'staff', name='user_role'), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.UniqueConstraint('user_id', name='user_id_unique')
    )
    op.create_table('comment_votes',
    sa.Column('user_id', sa.CHAR(length=255), nullable=True),
    sa.Column('issue_event_id', sa.Uuid(), nullable=True),
    sa.Column('voted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['issue_event_id'], ['issue_events.event_id'], name='comment_votes_issue_event_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='comment_votes_user_id_fkey')
    )
    op.create_table('department_members',
    sa.Column('user_id', sa.CHAR(length=255), nullable=True),
    sa.Column('department', sa.Enum('horticulture', 'engineering unit', name='department_enum'), nullable=True),
    sa.Column('roles', sa.Enum('manager', 'worker', name='departmental_roles'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='department_members_user_id_fkey'),
    sa.UniqueConstraint('user_id', name='unique_user_id')
    )
    op.create_table('issue_list',
    sa.Column('user_id', sa.CHAR(length=255), nullable=True),
    sa.Column('issue_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.issue_id'], name='issue_list_issue_id_fkey')
    )
    op.create_table('issue_subscriptions',
    sa.Column('user_id', sa.CHAR(length=255), nullable=True),
    sa.Column('issue_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.issue_id'], name='issue_subscriptions_issue_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='issue_subscriptions_user_id_fkey')
    )
    op.create_table('issue_votes',
    sa.Column('user_id', sa.CHAR(length=255), nullable=True),
    sa.Column('issue_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.issue_id'], name='issue_votes_issue_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='issue_votes_user_id_fkey')
    )
    op.create_table('session',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.CHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='session_user_id_fkey'),
    sa.PrimaryKeyConstraint('session_id', name='session_pkey')
    )
    op.create_index('idx_sessions_user_id', 'session', ['user_id'], unique=False)
    op.create_table('assignees',
    sa.Column('assignee_id', sa.CHAR(length=255), nullable=True),
    sa.Column('issue_id', sa.Uuid(), nullable=True),
    sa.Column('assigner_id', sa.CHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['department_members.user_id'], name='assignees_assignee_id_fkey'),
    sa.ForeignKeyConstraint(['assigner_id'], ['department_members.user_id'], name='assignees_assigner_id_fkey'),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.issue_id'], name='assignees_issue_id_fkey')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assignees')
    op.drop_index('idx_sessions_user_id', table_name='session')
    op.drop_table('session')
    op.drop_table('issue_votes')
    op.drop_table('issue_subscriptions')
    op.drop_table('issue_list')
    op.drop_table('department_members')
    op.drop_table('comment_votes')
    op.drop_table('users')
    op.drop_table('issues')
    op.drop_table('issue_events')
    # ### end Alembic commands ###
